name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set Up Java 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build the Application
        run: mvn clean package

      - name: Run Unit Tests
        run: mvn test

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Trigger Jenkins Deployment
        run: |
          curl -X POST "https://325e-109-52-113-113.ngrok-free.app/job/Sampath-tomcat-dp/build?token=Assured-Token=${{ secrets.JENKINS_API_TOKEN }}"
        env:
          JENKINS_USER: ${{ secrets.JENKINS_USER }}
          JENKINS_API_TOKEN: ${{ secrets.JENKINS_API_TOKEN }}
